backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "wallpapers"
    label: "Wallpapers"
    files:
      - label: "Wallpapers"
        name: "all_wallpapers"
        file: "public/wallpapers.json"
        widget: "list"
        fields:
          - {name: id, label: ID, widget: string, hint: "A unique ID, e.g., nature001"}
          - {name: title, label: Title, widget: string}
          - name: author
            label: Author
            widget: object
            fields:
              - {name: name, label: "Author Name", widget: string}
              - {name: title, label: "Author Title", widget: string}
          - {name: category, label: Category, widget: string}
          - {name: tags, label: Tags, widget: list, hint: "Press enter after each tag"}
          - name: download_options
            label: "Download Options"
            widget: "list"
            summary: "{{fields.resolution}} | {{fields.path}}"
            fields:
              - {name: resolution, label: Resolution, widget: select, options: ["1080p", "2K", "4K", "8K", "Mobile"]}
              - {name: path, label: "File (Upload Here)", widget: file}
